---
- name: "Installation Elastic on DC"
  hosts: dc
  gather_facts: false
  tasks:
    - name: "Download Elastic Agent"
      win_shell: |
        Invoke-WebRequest -Uri https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.9.0-windows-x86_64.zip -OutFile elastic-agent-8.9.0-windows-x86_64.zip
      args:
        executable: powershell.exe

    - name: "Extract Elastic Agent Archive"
      win_shell: |
        Expand-Archive .\elastic-agent-8.9.0-windows-x86_64.zip -DestinationPath .
      args:
       executable: powershell.exe
       
    - name: "Install in Archive"
      win_shell: |
        cd elastic-agent-8.9.0-windows-x86_64
      args:
       executable: powershell.exe

    - name: "Install Elastic Agent"
      win_shell: |
        ..\elastic-agent.exe install --url=https://10.202.0.109:8220 --enrollment-token=YWVabEZvd0JIaU1GTExNaU02VXg6d2Q4MHZ6OW9UQzZabGJ0Z29MNlNrUQ== --insecure -f
      args:
        executable: powershell.exe

